# This module tries to find libWebsockets library and include files
#
# LIBWEBSOCKETS_ROOT_DIR, path to install of libwebsockets
# LIBWEBSOCKETS_INCLUDE_DIR, path where to find libwebsockets.h
# LIBWEBSOCKETS_LIBRARY_DIR, path where to find libwebsockets.so
# LIBWEBSOCKETS_LIBRARIES, the library to link against
# LIBWEBSOCKETS_FOUND, If false, do not try to use libWebSockets
#
# This currently works probably only for Linux
IF ( NOT DEFINED LIBWEBSOCKETS_ROOT_DIR )
SET ( LIBWEBSOCKETS_ROOT_DIR $ENV{LIBWEBSOCKETS_ROOT_DIR} )
ENDIF ( NOT DEFINED LIBWEBSOCKETS_ROOT_DIR )

FIND_PATH ( LIBWEBSOCKETS_INCLUDE_DIR libwebsockets.h
    HINTS
        "${LIBWEBSOCKETS_ROOT_DIR}"
        "${LIBWEBSOCKETS_ROOT_DIR}/include"
    PATHS
        /usr/local/include
        /usr/include
)

FIND_LIBRARY ( LIBWEBSOCKETS_LIBRARIES websockets
    HINTS
        "${LIBWEBSOCKETS_ROOT_DIR}"
        "${LIBWEBSOCKETS_ROOT_DIR}/lib"
    PATHS
        /usr/local/lib
        /usr/lib
)

GET_FILENAME_COMPONENT( LIBWEBSOCKETS_LIBRARY_DIR ${LIBWEBSOCKETS_LIBRARIES} PATH )

SET ( LIBWEBSOCKETS_FOUND "NO" )
IF ( LIBWEBSOCKETS_INCLUDE_DIR )
    IF ( LIBWEBSOCKETS_LIBRARIES )
        SET ( LIBWEBSOCKETS_FOUND "YES" )
    ENDIF ( LIBWEBSOCKETS_LIBRARIES )
ENDIF ( LIBWEBSOCKETS_INCLUDE_DIR )

MARK_AS_ADVANCED(
    LIBWEBSOCKETS_LIBRARY_DIR
    LIBWEBSOCKETS_INCLUDE_DIR
    LIBWEBSOCKETS_LIBRARIES
)