name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"

env:
  LINUX_BREW: /home/linuxbrew/.linuxbrew/bin/brew
  LIBWEBSOCKETS_URL: https://libwebsockets.org/repo/libwebsockets
  LIBWEBSOCKETS_REVISION: b0a749c8e7a8294b68581ce4feac0e55045eb00b
  LIBWEBSOCKETS_FLAGS: |
    -DLWS_WITHOUT_TESTAPPS=On
    -DLWS_WITHOUT_TEST_SERVER=On
    -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=On
    -DLWS_WITHOUT_TEST_PING=On
    -DLWS_WITHOUT_TEST_CLIENT=On
    -DLWS_WITH_MINIMAL_EXAMPLES=Off
    -DLWS_WITH_SSL=Off

jobs:
  amd64_linux_clang:
    runs-on: ubuntu-latest
    env:
      CC: clang
      LIBWEBSOCKETS_ROOT_DIR: /home/linuxbrew/.linuxbrew/Cellar/libwebsockets/4.3.2
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt install -y make clang
          $LINUX_BREW install libwebsockets
      - run: clang --version
      - name: Build libws
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
      - name: Test libws
        run: |
          cd build
          cmake --build . --target test ARGS="-V"
  amd64_linux_gcc:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      LIBWEBSOCKETS_ROOT_DIR: /home/linuxbrew/.linuxbrew/Cellar/libwebsockets/4.3.2
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt install -y make gcc
          $LINUX_BREW install libwebsockets
      - run: gcc --version
      - name: Build libws
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
      - name: Test libws
        run: |
          cd build
          cmake --build . --target test ARGS="-V"
  amd64_macos_clang:
    runs-on: macos-latest
    env:
      CC: clang
      LIBWEBSOCKETS_ROOT_DIR: /usr/local/Cellar/libwebsockets/4.3.2
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl@3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          brew install openssl libwebsockets
      - run: cc --version
      - name: Build libws
        run: |
          mkdir -p build
          cd build
          cmake .. -DLWS_WITH_TLS=Off
          cmake --build .
      - name: Test libws
        run: |
          cd build
          cmake --build . --target test ARGS="-V"
  amd64_macos_gcc:
    runs-on: macos-latest
    env:
      CC: gcc-11
      LIBWEBSOCKETS_ROOT_DIR: /usr/local/Cellar/libwebsockets/4.3.2
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl@3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          brew install gcc@11 openssl libwebsockets
      - run: gcc-11 --version
      - name: Build libws
        run: |
          mkdir -p build
          cd build
          cmake .. -DLWS_WITH_TLS=Off
          cmake --build .
      - name: Test libws
        run: |
          cd build
          cmake --build . --target test ARGS="-V"
  amd64_windows_clang:
    runs-on: windows-2019
    env:
      CC: clang
      LIBWEBSOCKETS_ROOT_DIR: C:\\msys64\\usr
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Dependencies
        run: |
          pacman --version
          pacman -Sy
          pacman --noconfirm -S pacman-mirrors
          pacman --noconfirm -S mingw64/mingw-w64-x86_64-clang mingw64/mingw-w64-x86_64-libwebsockets
          echo "C:\\msys64\\mingw64\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: clang --version
      - name: Build libws
        run: |
          mkdir -p build
          cd build
          cmake .. -G "MinGW Makefiles"
          cmake --build .
      - name: Test libws
        run: |
          cd build
          cmake --build . --target test ARGS="-V"
  amd64_windows_gcc:
    runs-on: windows-2019
    env:
      CC: gcc
      LIBWEBSOCKETS_ROOT_DIR: C:\\msys64\\usr
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Dependencies
        run: |
          pacman --version
          pacman -Sy
          pacman --noconfirm -S pacman-mirrors
          pacman --noconfirm -S mingw-w64-x86_64-libwebsockets
          echo "C:\\msys64\\mingw64\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: gcc --version
      - name: Build libws
        run: |
          mkdir -p build
          cd build
          cmake .. -G "MinGW Makefiles"
          cmake --build .
      - name: Test libws
        run: |
          cd build
          cmake --build . --target test ARGS="-V"
