name: CI docs

on:
  push:
    paths-ignore:
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "LICENSE"

env:
  LINUX_BREW: /home/linuxbrew/.linuxbrew/bin/brew

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      LIBWEBSOCKETS_ROOT_DIR: /home/linuxbrew/.linuxbrew/Cellar/libwebsockets/4.3.2
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz python3-pip
          pip install breathe sphinx
          pip install -r docs/requirements.txt
          $LINUX_BREW install libwebsockets
      - name: Build docs
        run: |
          mkdir -p build
          cd build
          cmake .. -DLIBWS_DOXYGEN=ON -DLIBWS_UNIT_TESTING=OFF
          cmake --build .
